#钱包里的一个地址的私钥,unisat钱包导出私钥可以看到（最后一栏 Hex Private Key）,
#注意：配置好私钥后，先运行命令 “ go run . ”，程序会将对应地址导入到本地节点，之后再将btc充值到这个地址上，之所以这样是因为会检测不到导入前地址上的余额
PrivateKey: "" 


Mint:
  RuneId: "1:0"  #Mint符文，修改RuneId
  MintNum: 1    #mint几张


#gas费率 设置为0的时候会自动使用链上gas，可能会偏高
FeePerByte: 25
 
#本地的rpc节点btc:btc，一个是用户名一个是密码，根据自己的改
LocalRpcUrl: "http://btc:btc@127.0.0.1:8885"

#是否启动自动加速，启动的话当UTXO到达25的时候，则会自动获取当前区块gas进行无限次加速（条件当前utxo上请保证足够余额）, 
#1：加速； 0不加
IsAutoSpeed: 1 
#当需要加速的时候，卡着的每笔交易想加速到多少gas，如果设置为0，则会自动从链上获取当前区块gas
SpeedFee: 5 



#不需要动，获取当前区块gas时候会用到，这种方式相对准确
Network: "mainnet" # mainnet 
RpcUrl: "https://mempool.fractalbitcoin.io/api" #https://mempool.space/api https://mempool.space/testnet/api
UtxoAmount: 330
