WalletName: "" #钱包名字， 后面必须要使用这个钱包下面的地址打
PrivateKey: ""  #钱包里的一个地址的私钥,unisat钱包导出私钥可以看到（最后一栏 Hex Private Key）

#Mint符文，修改RuneId
Mint:
  RuneId: "1:0"



#不需要动
Network: "mainnet" # mainnet 
RpcUrl: "https://mempool.fractalbitcoin.io/api" #https://mempool.space/api https://mempool.space/testnet/api
FeePerByte: 5
UtxoAmount: 330

#部署符文，修改下面
Etching:
  Rune: "TEST"
  Symbol: "TEST"
  Premine: 1000000
  Amount: 1000
  Cap: 20000
#  Divisibility: 0
#  HeightStart: 0
#  HeightEnd: 0
#  HeightOffsetStart: 0
#  HeightOffsetEnd: 0
